export const products = [
    {
        id:'1',
        img:'assets/simona.jpg'
    },
    {
        id:'2',
        img:'assets/eric.jpg'
    },
    {
        id:'3',
        img:'assets/joshua.jpg'
    },
    {
        id:'5',
        img:'assets/eduardo.jpg'
    },
    {
        id:'6',
        img:'assets/pic8.jpg'
    },
    {
        id:'7',
        img:'assets/subhajit.jpg'
    },
    {
        id:'8',
        img:'assets/michael.jpg'
    },
    {
        id:'9',
        img:'assets/caroline.jpg'
    },
    {
        id:'10',
        img:'assets/andres.jpg'
    },
    {
        id:'11',
        img:'assets/ashley.jpg'
    },
    {
        id:'12',
        img:'assets/eduardo.jpg'
    },
    {
        id:'13',
        img:'assets/suheyl.jpg'
    },
    {
        id:'14',
        img:'assets/eduardo.jpg'
    },
    {
        id:'15',
        img:'assets/taylor.jpg'
    },
    {
        id:'16',
        img:'assets/aydin-polaris.jpg'
    },
]